### ISSUE TITLE
Submitting an Event

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/design#17]
![screenshot 2017-03-08 22 11 05](https://cloud.githubusercontent.com/assets/25624431/23742894/c57b9de6-0452-11e7-9053-8bf0ec2da2b6.png)

**Comment by InciteDemocracy** [comment]
![screenshot 2017-03-08 18 11 09](https://cloud.githubusercontent.com/assets/25624431/23743046/3f6337c2-0453-11e7-859c-869ccc04891a.png)

**Comment by InciteDemocracy** [comment]
Just posting these mockups to start any needed discussion about adding events.

**Comment by bripenney** [comment]
When people add events, what information do we want them to be able to post?

Some ideas:
- Title
- Description
- Date
- Length
- Location
- Photo
- Organization
- Link to event
- Your email (as a note, should people have to login as a user to create integrity for events? This way we can stop any sort of spamming. Perhaps a lower barrier of entry to attend, but to create we need a little more info about who you are, if you're part of an organization etc.)


It might need to be its own page rather than a drop down if there are a lot of options, but regardless it should be easy to navigate to.

**Comment by InciteDemocracy** [comment]
For the initial MVP we want to keep the threshold of participation (submitting events) to a absolute minimum. For later versions we may add a "more options" button to the form that expands the event submission menu to include more fields. For now this stripped down version makes sense to me.

**Comment by bripenney** [comment]
Cool okay. Is the idea then that all of these events are already on other sites and we're scraping the extra info from there?

**Comment by nicholasswanson** [comment]
@InciteDemocracy @bripenney I think there is potentially a lot we could explore here, so I'd like to close this out for 1.0 while keeping this as an area to continue to push on.
