### ISSUE TITLE
List items UX

### ISSUE THREAD

**Issue by nicholasswanson** [ResistanceCalendar/design#3]
<img width="315" alt="screen shot 2017-03-02 at 9 08 41 pm" src="https://cloud.githubusercontent.com/assets/3856906/23538964/7e31e604-ff8c-11e6-9004-59895718276f.png">
<img width="321" alt="screen shot 2017-03-02 at 9 08 51 pm" src="https://cloud.githubusercontent.com/assets/3856906/23538965/7e36abda-ff8c-11e6-9af6-6b38576920ae.png">

* Refine and create consistent mobile+desktop layouts
* Metadata to include/exclude/prioritize (attendees, location, time of day, tags, etc.)
* How many events do we show before asking to load more?

**Comment by nicholasswanson** [comment]
* Align text to left and image right for scannability
* All same font size (base)
* Entire cell is tappable, but tags are also tappable (takes to "search results" screen)

<img src="https://cloud.githubusercontent.com/assets/3856906/23690618/e5fce7e0-0377-11e7-846d-facc00c9e6df.png">

**Comment by InciteDemocracy** [comment]
Looks good, I think putting the images on the right is a good solution. We need to clearly display the day that events are on. Here is an example of how some calendars handle it: 

![screenshot 2017-03-08 09 26 05](https://cloud.githubusercontent.com/assets/25624431/23720048/a29465ea-03e1-11e7-86d5-8c7c39c58a1d.png)

Adding the day+date to each event card is the simplest solution: 

![screenshot 2017-03-08 11 49 44](https://cloud.githubusercontent.com/assets/25624431/23728058/e8353c9c-03fe-11e7-9e2c-8d20636f33d8.png)

**Comment by dentemple** [comment]
I do like what InciteDemocracy has, especially for mobile.  One small addition I would suggest is to assign each day of the week a different background color.  So that the background for `FRI` in `FRI | MAR 6` would always have one color; the background for `SAT` in `SAT | MAR 7` would always have its own color; and so on and so forth.

On the desktop version (which would have more real estate), having the calendar icon floating the left would be really cool, too.

**Comment by InciteDemocracy** [comment]
I know it's annoying to spend all that screen space on the repeating date but I think this may be the best bet for the MVP. If we have time to spare at some point it would be very cool to experiment with something like the react-sticky you suggested: https://www.npmjs.com/package/react-sticky

**Comment by bripenney** [comment]
![home](https://cloud.githubusercontent.com/assets/24579735/23837298/fbb36638-0753-11e7-92ac-c34916d58ffb.png)
I uploaded this on another thread, but this may be the correct place to discuss this. Not sure. I decided to condense the time in with the date due to the potential for longer names of events.

**Comment by nicholasswanson** [comment]
I think the list items are generally set, with potential design tweaks we could make down the road. Don't want to hold up dev.
